spring:
  application:
    name: cloud-config-server
  profiles:
      active: dev
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wenthywangtee/config-repo
          username: 13660783361
          password: Wwh13660783361
          search-paths: /**
      label: master

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
---
spring:
  profiles: dev
server:
    port: 8003
logging:
  level:
       root: info
  path: D:/logs
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 30
    serviceUrl:
      defaultZone: http://wwh:wwh@111.230.24.31:8002/eureka,http://wwh:wwh@47.106.88.213:8002/eureka
---
spring:
  profiles: docker
logging:
  path: /logs
  level:
        root: info
server:
  port: ${SERVICE_PORT}
eureka:
  environment: docker
  instance:
    hostname: ${SERVICE_HOST}
    port: ${server.port}
    leaseRenewalIntervalInSeconds: 30
    health-check-url-path: /actuator/health
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_URL}
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false






