version : '3'
services:

service-people:
        image: "wenthywang/service-people"
        ports:
                - "8082:8082"
        environment:
          JAVA_OPTS: -Xmx256m -Xms256m
        volumes:
            - /usr/local/wwh/logs:/log