spring:
  application:
    name: eureka-server

server:
      port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: false



